# Generated by Django 2.2.4 on 2019-08-14 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='thumb',
            field=models.ImageField(blank=True, default='1.png', null=True, upload_to='news_thumb'),
        ),
    ]
