# Generated by Django 2.2.4 on 2019-08-14 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20190814_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='thumb',
            field=models.ImageField(default='1.png', upload_to='news_thumb'),
        ),
    ]
