# Generated by Django 2.2.4 on 2019-08-25 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20190825_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='thumb',
            field=models.ImageField(default='default_new.jpg', upload_to='news_thumb/'),
        ),
    ]
