# Generated by Django 2.2.4 on 2019-08-15 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20190814_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='thumb',
            field=models.ImageField(default='1.png', upload_to='news_thumb/'),
        ),
    ]
